identifier: ie_site_template
rootPageId: 1
websiteTitle: Image Engineering
base: /
baseVariants:
  - identifier: development
    base: http://localhost:8080/
    condition: 'applicationContext == "Development"'
  - identifier: production
    base: https://www.image-engineering.example/
    condition: 'applicationContext == "Production"'
languages:
  - title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    fallbackType: strict
    fallbacks: ''
  - title: Deutsch
    enabled: true
    languageId: 1
    base: /de/
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    fallbackType: strict
    fallbacks: '0'
errorHandling:
  - errorCode: '404'
    errorHandler: Fluid
    options:
      templatePathAndFilename: 'EXT:ie_site_template/Resources/Private/Templates/Error/404.html'
  - errorCode: '403'
    errorHandler: Fluid
    options:
      templatePathAndFilename: 'EXT:ie_site_template/Resources/Private/Templates/Error/403.html'
sitemap:
  generator: default
  pages:
    -
      rootPageId: 1
      priority: 0.5
