identifier: main
rootPageId: 1
base: 'https://image-engineering.test/'
defaultLanguage: 0
languages:
  - title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    flag: gb
errorHandling:
  - errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=4'
routes: { }
routeEnhancers: { }
imports:
  - resource: 'EXT:site_template/Configuration/Sets/SitePackage/config.yaml'
