rootPageId: 1
base: 'https://www.image-engineering.de/'
languages:
  - title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    iso-639-1: en
    flag: gb
    navigationTitle: English
  - title: Deutsch
    enabled: true
    languageId: 1
    base: /de/
    locale: de_DE.UTF-8
    iso-639-1: de
    flag: de
    navigationTitle: Deutsch
errorHandling:
  - errorCode: 404
    errorHandler: Fluid
    options:
      templateFile: 'EXT:ie_site_template/Resources/Private/Templates/Error/404.html'
      variables:
        siteName: 'Image Engineering'
  - errorCode: 403
    errorHandler: Fluid
    options:
      templateFile: 'EXT:ie_site_template/Resources/Private/Templates/Error/403.html'
      variables:
        siteName: 'Image Engineering'
routes: {  }
websiteTitle: 'Image Engineering'
