identifier: ie-site
rootPageId: 1
base: 'https://p-cfmuvv.project.space/'
baseVariants: {  }
errorHandling:
  - errorCode: 404
    errorHandler: Fluid
    options:
      templateFile: EXT:ie_site_template/Resources/Private/Templates/Page/Error404.html
languages:
  - title: English
    navigationTitle: English
    base: /
    locale: en_US
    iso-639-1: en
    hreflang: en-US
    direction: ltr
    languageId: 0
    flag: gb
websiteTitle: 'Image Engineering'
